In [ ]:
# Author: Hicham Ait Douch
# 🎓 Computer Science Student | Machine Learning & AI Enthusiast

# 🔗 GitHub: https://github.com/hicham-codeio
# 🔗 LinkedIn: https://linkedin.com/in/hicham-ait-douch
# 🔗 Kaggle: https://kaggle.com/hichamaitdouch

                            Step 1 : LowerCase

In [ ]:
sentence = "What is Machine Learning ?? Algorithms is field of data science : that use to predict! result from an input by training on patterns so to predict an output ."
sentence_lower = [word.lower() for word in sentence.split()]
sentence_lower

                            step 2 : Removing Stop Word

In [ ]:
import nltk  #nltk.download('stopwords')
from nltk.corpus import stopwords

In [ ]:
en_stopwords = stopwords.words('english')
sentence_no_stopwords = ' '.join([word for word in sentence_lower if word not in en_stopwords])
sentence_no_stopwords

                            step 3 : Remove & Adding & Filtering Sentence

In [ ]:
import re
result_search = re.search('machine' ,sentence_no_stopwords)
to_search = {'start':'^a', 'end':'z$', 'multipl':r"['need']['want']ed"}
to_filter = r"[^\w\s]"
clean_sentence = re.sub(to_filter, '',sentence_no_stopwords)
clean_sentence

In [ ]:
ai_info =["python is a powerful language use in ai",
          "RAG is concept that work like library of information",
          "fine funning is concept to add training to model",
          "llm is arche that let ai prodict the the freq common word"]
pattern_review = []
patterns_to_find = r'fine tunning and RAG are powrfuls concepts'
for sentence in ai_info :
    for pattern in patterns_to_find.split() :
        if (re.search(pattern ,sentence)) :
            pattern_review.append(sentence)
pattern_review

                            Step 4 : Tokenization

In [ ]:
import nltk #nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize ,sent_tokenize
sentence_add_comma = clean_sentence +". deep learning inspired humain's brain"
sent_tokenize(sentence_add_comma)
word_tokenize(sentence_add_comma)

                            Step 5 :Stemming (remove ending/suffix)

In [ ]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
program_tokens = ['programs', 'programming', 'programmers', 'programmation', 'programmed']
for token in program_tokens :
    print(token, ':', ps.stem(token))

                            Step 5 : Lemmatizition (more meaninful)

In [ ]:
from nltk.stem import WordNetLemmatizer #nltk.download('wordnet
lemmatizer = WordNetLemmatizer()
for token in program_tokens:
    print(token, ':' ,lemmatizer.lemmatize(token))

                            Step 6 : N-gram(sequence of neighbers tokens or word)(N most commen words)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
sentence_to_list = sentence_add_comma.split()
unigrams = (pd.Series(nltk.ngrams(sentence_to_list, 1))).value_counts()
bigrams = (pd.Series(nltk.ngrams(sentence_to_list, 2))).value_counts()
unigrams[:10].sort_values().plot.barh(width=9, figsize=(14,8))

                                Powerful Prictical Exercice

In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer

In [2]:
data = pd.read_csv("10. tripadvisor_hotel_reviews.csv")
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [3]:
data['Review_process'] = data['Review'].str.lower()
data.head()

,Review,Rating,Review_process
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [5]:
en_stopwords = stopwords.words('english')
en_stopwords.remove('not')
data['Review_process'] = data['Review'].apply(lambda x : ' '.join([word for word in x.split() if word not in en_stopwords]))
data.Review_process[0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe noisy neighbors, aveda bath products nice, not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience pay 40 parking night,'

In [ ]:
data['Review_process'] = data.apply(lambda x : re.sub(r'[*]', ' star', x['Review_process']), axis=1)
data['Review_process'] = data.apply(lambda x : re.sub(r'[^\s\w]', '', x['Review_process']), axis=1)

In [ ]:
data.head()

In [ ]:
data['Review_tokens'] = data.apply(lambda x : word_tokenize(x['Review_process']), axis=1)

In [ ]:
data.head()

In [ ]:
ps = PorterStemmer()
data['stemm_review'] = data['Review_tokens'].apply(lambda tokens : [ps.stem(token) for token in tokens])

In [ ]:
lm = WordNetLemmatizer()
data['lemmatizer_review'] = data['Review_tokens'].apply(lambda tokens : [lm.lemmatize(token) for token in tokens])

In [ ]:
data.head()

In [ ]:
clean_tokens = sum(data['lemmatizer_review'],[])
unigram = pd.Series(nltk.ngrams(clean_tokens ,1)).value_counts()
bigram = pd.Series(nltk.ngrams(clean_tokens ,2)).value_counts()
print(unigram[:5])
print(bigram[:5])