SpaCy is a library for Natural Language Processing (NLP). It allows you to analyze and 
understand text with Python, Used to :  
• Split a sentence into individual words or punctuation marks (called tokens). 
• Figure out what grammatical role each word plays (called part-of-speech or POS 
tagging), such as noun, verb, or adjective.

In [2]:
import spacy
import pandas as pd
nlp = spacy.load('en_core_web_sm') #load the English model vocabulary, grammar rules, and statistical patterns.

In [3]:
text = "Artificial Intelligence (AI) is transforming industries around the world. Companies like Google, Microsoft, and OpenAI are investing billions of dollars into research and development to create smarter systems. In 2023, researchers at Stanford University published studies showing that AI models can assist doctors in diagnosing diseases more accurately. Governments in countries such as the United States, Germany, and Japan are also creating regulations to ensure AI is used responsibly. Meanwhile, entrepreneurs in cities like San Francisco and London are launching startups that apply machine learning to finance, transportation, and education."
spacy_text =nlp(text)
df_pos = pd.DataFrame(columns=["Token" ,"POS_tag"])

for token in spacy_text :
    df_pos = pd.concat([df_pos,
                        pd.DataFrame([{"Token":token.text ,"POS_tag" : token.pos_}])],ignore_index=True)

df_pos.head(3)

          Token POS_tag
0    Artificial   PROPN
1  Intelligence   PROPN
2             (   PUNCT

In [4]:
df_pos_counts = df_pos.groupby(['Token' ,'POS_tag']).size().reset_index(name='counts').sort_values(by='counts' ,ascending=False)
df_pos_counts.head(10)

   Token POS_tag  counts
2      ,   PUNCT       8
3      .   PUNCT       5
26   and   CCONJ       5
5     AI   PROPN       3
28   are     AUX       3
48    in     ADP       3
75    to    PART       2
73   the     DET       2
55  like     ADP       2
52    is     AUX       2

In [ ]:
df_pos_pos_counts = df_pos_counts.groupby(['POS_tag'])['Token'].count().sort_values(ascending=False)
df_pos_pos_counts.head(10)
nouns = df_pos_counts[df_pos_counts.POS_tag == 'NOUN'][:10]
nouns